### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by mjerkovic91** [hvarga/arhixml#1]
I am trying to build the project as described but ant cannot build it.

It says:

BUILD FAILED
C:\ArhiXML\build.xml:28: Compile failed; see the compiler error output for details.

**Comment by hvarga** [comment]
I have fixed build issues in so you can pull the latest changes and try again.

I have also implemented Docker Image for ArhiXML. So I recommend to follow the newest version of `README.md` as it contains the steps to run ArhiXML using the Docker. This is the recommended way of running ArhiXML.
